services:
  - type: web
    name: photo-reader-backend
    env: python
    plan: free
    region: oregon
    # Lock Python version for compatibility
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd backend && gunicorn wsgi:app --bind 0.0.0.0:$PORT \
        --workers=1 --threads=1 --timeout=180 --max-requests=25 --max-requests-jitter=10
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: OCR_MAX_WIDTH
        value: "1600"
      # Set this to 1 if memory pressure occurs due to EasyOCR/torch
      - key: OCR_DISABLE_EASYOCR
        value: "0"
      # Example to disable Tesseract if binary not installed in image
      - key: OCR_DISABLE_TESSERACT
        value: "0"
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      # Free tier concurrency is limited; keep a single worker + threads minimal.

staticSites:
  - name: photo-reader-frontend
    # Directory containing index.html
    buildCommand: |
      echo "window.BACKEND_URL=window.BACKEND_URL||'${BACKEND_URL:-https://textify-b0iv.onrender.com}'" > frontend/config.js
    publishPath: frontend
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    environment:
      - key: BACKEND_URL
        value: https://textify-b0iv.onrender.com
    # Provide a health check path if desired (Render optional for static)
    # routes can be added if using client-side routing later
