# Render deployment configuration
# Place this in the root directory

# Build command (what Render runs to prepare your app)
# pip install -r requirements.txt

# Start command (how Render starts your app)
# cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

# Environment variables to set in Render dashboard:
# PYTHON_VERSION=3.12
# PORT=10000 (automatically set by Render)